package com.tarsier.util;

public interface Constant {
	String	COLON				= ":";
	String	COMMA				= ",";
	String	TAB					= "\t";
	String	UNDER_LINE			= "_";
	char	EQUAL				= '=';
	String	OR					= "\\|\\|";
	String	MINUS				= "-";
	String	IP					= "ip";
	String	CREATE_TIME			= "createTime";
	String	UPDATE_TIME			= "updateTime";
	String	URL					= "url";
	String	REF					= "ref";
	String	AGENT				= "agent";

	String	SEP_POINT			= "\\.";
	String	BLANK_SPACE			= " ";
	String	DELIMMER			= "/";
	String	ITEM				= "item";
	String	ITEMS				= "items";
	String	RESULT				= "result";
	String	SUCCESS				= "success";
	String	SUCCESS_STRING		= "\"success\"";
	String	OK					= "ok";
	String	FAIL				= "fail";
	String	TRUE				= "true";
	String	FALSE				= "false";
	String	EXCEPTION			= "exception";
	String	WARN				= "warn";
	String	ERROR				= "error";
	String	JSON_PAGE			= "json";
	String	TEXT_PAGE			= "text";
	String	ID					= "id";
	String	NAME				= "name";
	String	DESCRIPTION			= "description";
	String	IDS					= "ids";
	String	SYNC				= "sync";
	String	X_FORWARDED_FOR		= "x-forwarded-for";


	String	UTC_TIME_STAMP		= "@timestamp";
	String	TIME_STAMP			= "timestamp";
	String	PROJECT_NAME		= "projectName";
	String	MESSAGE				= "message";
	String	VERSION				= "@version";
	String	TYPE				= "type";
	String	LOG_CATEGORY		= "logCategory";
	String	HOST				= "host";
	String	PATH				= "path";
	String	LOG_LEVEL			= "logLevel";
	String	LOGGER				= "logger";
	String	EVENT_TYPE			= "eventType";
	String	DISPATH_THREAD_NAME	= "dispatch-log2rulechains";
	String	CHAIN_ID			= "chain_id_";
	String	OBJECT				= "object";
	String	DATA				= "data";
	String	MD5					= "md5";
	String	FS					= "fs";
	String	KAFKA				= "kafka";
	String	INIT				= "init";
	String	RULESVR_ID			= "ruleId";
	String	RED					= "red";
	String	YELLOW				= "yellow";
	String	GREEN				= "green";
	String	LAST_LOG			= "lastLog";
	String	LAST_ALARM			= "lastAlarm";
	String	CLUSTER				= "cluster";
	String	ON_LINE				= "在线";
	String	OFF_LINE			= "离线";
	String	DISABLED			= "已停用";
	String EMAIL_SUFFIX			="@email.cn";
}
